### ISSUE TITLE
course at pluralsight

### ISSUE THREAD

**Issue by torontom** [DeborahK/Angular-TypeScript#4]
The pluralsight course "Angular with TypeScript" does sound like generated by robot....and no face showing makes me skeptical..

**Comment by DeborahK** [comment]
I blame 7 of 9, "computer" from StarTrek, and "android" from Dark Matter. They all just copied my voice. :-(

But I have to say, some days I really wish I was a computer voice because then I would not feel so sad when I get these comments. I assume this was just meant to be hurtful and I can close this as a real issue?
